export enum Pose {
    DYING = 'DYING',
    FALL_FLYING = 'FALL_FLYING',
    SLEEPING = 'SLEEPING',
    SNEAKING = 'SNEAKING',
    SPIN_ATTACK = 'SPIN_ATTACK',
    STANDING = 'STANDING',
    SWIMMING = 'SWIMMING'
}
