export enum BlockAction {
    LEFT_CLICK_AIR = 'LEFT_CLICK_AIR',
    LEFT_CLICK_BLOCK = 'LEFT_CLICK_BLOCK',
    PHYSICAL = 'PHYSICAL',
    RIGHT_CLICK_AIR = 'RIGHT_CLICK_AIR',
    RIGHT_CLICK_BLOCK = 'RIGHT_CLICK_BLOCK'
}
